/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AbacusRouteImport } from './routes/abacus'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LibrarySlugRouteImport } from './routes/library.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbacusRoute = AbacusRouteImport.update({
  id: '/abacus',
  path: '/abacus',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrarySlugRoute = LibrarySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LibraryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abacus': typeof AbacusRoute
  '/library': typeof LibraryRouteWithChildren
  '/library/$slug': typeof LibrarySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abacus': typeof AbacusRoute
  '/library': typeof LibraryRouteWithChildren
  '/library/$slug': typeof LibrarySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abacus': typeof AbacusRoute
  '/library': typeof LibraryRouteWithChildren
  '/library/$slug': typeof LibrarySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/abacus' | '/library' | '/library/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/abacus' | '/library' | '/library/$slug'
  id: '__root__' | '/' | '/abacus' | '/library' | '/library/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbacusRoute: typeof AbacusRoute
  LibraryRoute: typeof LibraryRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abacus': {
      id: '/abacus'
      path: '/abacus'
      fullPath: '/abacus'
      preLoaderRoute: typeof AbacusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$slug': {
      id: '/library/$slug'
      path: '/$slug'
      fullPath: '/library/$slug'
      preLoaderRoute: typeof LibrarySlugRouteImport
      parentRoute: typeof LibraryRoute
    }
  }
}

interface LibraryRouteChildren {
  LibrarySlugRoute: typeof LibrarySlugRoute
}

const LibraryRouteChildren: LibraryRouteChildren = {
  LibrarySlugRoute: LibrarySlugRoute,
}

const LibraryRouteWithChildren =
  LibraryRoute._addFileChildren(LibraryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbacusRoute: AbacusRoute,
  LibraryRoute: LibraryRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
